basic:
  exp_name: E0031_LightingDiT_XL_Flow_Dinov3_vitsp_BS256_cache_qknorm_wxs_learnable_latent_space
  results_dir: exps
  data_path: /m2v_intern/public_datasets/ImageNet-1k/data/train_images
  global_seed: 1234
  epochs: 1000
  log_every: 100
  ckpt_every: 50000
  rf: true
  rf_ori: false
  shift: 0.1
  accum_iter: 1
  clip_grad_norm: null
  image_size: 256
  global_batch_size: 1024
  num_workers: 12
  timestep_start: 0
  timestep_end: 1000
  encoder: dinov3_vitsp16
  feature_norm: true
  vae_path: stabilityai/sd-vae-ft-mse
  use_latent: false
  encoder_config: /ytech_m2v3_hdd/yuanziyang/sml/FVG/config/f16d32_ldm_dinov3_vitsp.yaml
model:
  ckpt: null
  target: models.lightningdit.LightningDiT
  params:
    input_size: 16
    num_classes: 1000
    patch_size: 1
    depth: 28
    hidden_size: 1152
    num_heads: 16
    use_qknorm: true
    use_swiglu: true
    use_rope: true
    use_rmsnorm: true
    wo_shift: false
    in_channels: 384
optim:
  base_learning_rate: 0.0002
  weight_decay: 0
  betas:
  - 0.9
  - 0.95
lr_sheduler:
  warmup: null
  train_epoch: null
