basic:
  exp_name: E0006_TCDiT_B_Flow_Dinov3_vitb_BS256
  results_dir: exps
  data_path: /m2v_intern/public_datasets/ImageNet-1k/data/train_images

  global_seed: 1234
  epochs: 1000 
  log_every: 100
  ckpt_every: 50000
  rf: True
  rf_ori: False
  discrete: False

  accum_iter: 1
  clip_grad_norm:    # set None to disable

  image_size: 256
  global_batch_size: 256
  num_workers: 8

  timestep_start: 0 
  timestep_end: 1000

  vae_path: stabilityai/sd-vae-ft-mse
  use_latent: False
  encoder: dinov3_vitb16


model:
  ckpt:
  target: models.models_TCDiT_dino.DiT
  params:
    input_size: 768
    num_classes: 1000
    patch_size: 2
    depth: 12
    hidden_size: 768
    num_heads: 12
    mlp_ratio: 4
    use_swiglu: false
    in_channels: 16
    MoE_config:
      num_experts: 16
      init_MoeMLP: false
      interleave: true
      num_experts_per_tok: 1
      granularity: 1
      n_shared_experts: 0
      aux_loss_alpha: 0.01


optim:
  base_learning_rate: 0.0001
  weight_decay: 0
  betas: [0.9, 0.999]


lr_sheduler:
  warmup:
  train_epoch:



