basic:
  exp_name: example_SVG_XL_BS256
  results_dir: exps
  data_path: /your_path/ImageNet-1k/data/train_images

  global_seed: 1234
  epochs: 1000 
  log_every: 100
  ckpt_every: 50000
  rf: True
  shift: 0.4

  accum_iter: 1
  clip_grad_norm:    # set None to disable

  image_size: 256
  global_batch_size: 256
  num_workers: 16

  timestep_start: 0 
  timestep_end: 1000
  encoder: dinov3_vitsp16
  feature_norm: true

  encoder_config: ../autoencoder/svg/configs/example_svg_autoencoder_vitsp.yaml

model:
  ckpt: 
  target: models.models_SVG.DiT
  params:
    input_size: 16
    num_classes: 1000
    patch_size: 1
    depth: 28
    hidden_size: 1152
    num_heads: 16
    mlp_ratio: 4
    use_swiglu: false
    in_channels: 392
    qk_norm: True
    class_dropout_prob: 0.1

optim:
  base_learning_rate: 0.0001
  weight_decay: 0
  betas: [0.9, 0.999]


